name: chikua
description: "Simple habit tracker app"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5+1
  intl: ^0.20.2
  keyboard_emoji_picker: ^1.0.3
  flutter_launcher_icons: ^0.14.4
  emoji_picker_flutter: ^4.4.0
  # libraries for local database management
  path_provider: ^2.1.5
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  flutter_slidable: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.13
  package_rename: ^1.10.1

flutter:
  uses-material-design: true

package_rename_config:
  android:
    app_name: "Chikua"
    package_name: "io.github.robertaguilera712.chikua"
    override_old_package: "com.example.habits" # This cleans up your old folder structure!
  ios:
    app_name: "Chikua"
    bundle_name: "Chikua"
    bundle_id: "io.github.robertaguilera712.chikua"
