name: upvia
description: "Simple habit tracker app"
publish_to: 'none'
version: 0.1.0+2

environment:
  sdk: ^3.9.2

isar_version: &isar_version 3.3.0 # define the version to be used


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.5+1
  intl: ^0.20.2
  keyboard_emoji_picker: ^1.0.3
  flutter_launcher_icons: ^0.14.4
  emoji_picker_flutter: ^4.4.0
  # libraries for local database management
  path_provider: ^2.1.5
  isar_community: 
    version: *isar_version
  isar_community_flutter_libs: # contains Isar Core
    version: *isar_version
  flutter_slidable: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  isar_community_generator: 
    version: *isar_version
  build_runner: any
  flutter_gen: ^5.12.0
  package_rename: ^1.10.1

flutter:
  uses-material-design: true
  generate: true

package_rename_config:
  android:
    app_name: "Upvia"
    package_name: "io.github.robertaguilera712.upvia"
    # override_old_package: "com.example.habits" # This cleans up your old folder structure!
    override_old_package: "io.github.robertaguilera712.chikua" # This cleans up your old folder structure!
  ios:
    app_name: "Upvia"
    bundle_name: "Upvia"
    bundle_id: "io.github.robertaguilera712.upvia"
